apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-apps
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: argocd-apps
  path: ./fluxCD/infra
  prune: true
  wait: true
  timeout: 5m
