---
ui:
  # -- (bool) Enable Policy Reporter UI
  enabled: true

metrics:
  # -- Enables Prometheus Metrics
  enabled: true

plugin:
  kyverno:
    # -- (bool) Enable Kyverno Plugin
    enabled: true

ingress:
  # -- Create Ingress
  # This ingress exposes the policy-reporter core app.
  enabled: true
  # -- Ingress className
  className: "traefik"
  # -- Labels for the Ingress
  labels: {}
  # -- Annotations for the Ingress
  annotations:
    # kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-cluster-issuer
    cert-manager.io/propagation-timeout: "30s"
    cert-manager.io/polling-interval: "5s"
  # -- Ingress host list
  hosts:
    - host: kyverno.home.lab
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: policy-reporter-ui
              port:
                number: 8080

  tls:
    - secretName: kyverno-tls
      hosts:
        - kyverno.home.lab
